import Head from "next/head";
import Header from "./Components/Header/Header";
import Typing from "./Components/Typing/Typing";

export default function Home() {

  
  return (
    <>
      <>
        <Head>
          <title>João | Portfólio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="./favicon.ico" />
        </Head>
        <Header />
        <main className="MainBox">
          <section className="ContentBox">
          <Typing FirstSentence="Oi, eu sou o João" SecondSentence="Desenvolvedor front-end."/>
      
          </section>
        </main>
      </>
    </>
  );
}
