import Head from "next/head";
import Header from "./Header/Header";
import Typing from "./Typing/Typing";
import { useEffect,useState } from "react";

export default function Home() {
  
  const [lang, setLang] = useState("pt-br")

  useEffect(() => {
    setLang(localStorage.getItem("lang"))
  }, [])

  return (
    <>
      <>
        <Head>
          <title>João Pedro Belo | Desenvolvedor Front-end</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="./favicon.ico" />
        </Head>
        
        <Header />
        
        <main className="MainBox">
          
          <section className="ContentBox">
          
          <Typing FirstSentence={ lang === "pt-br" || lang === null ? "Oi, eu sou o João": "Hiii, I'm João"} SecondSentence={ lang === "pt-br" || lang === null ? "Desenvolvedor front-end.": "Front-end Developer."}/>
          
          </section>
        </main>
      </>
    </>
  );
}
